import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata = {
  title: "Marketing Portfolio",
  description: "Generated by marketing Portfolio",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body>
       <Navbar/>
        {children}
       <div className="mt-20"> <Footer /></div>
      </body>
    </html>
  );
}
